config/routes.rb
Rails.application.routes.draw do
  
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save 
      redirect_to contacts_path
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to contacts_path
    else
      render :edit
    end
  end

  def destroy
    Contact.find(params[:id]).destroy 
    redirect_to contacts_path
  end



  private

  def contact_params
    params.require(:contact).permit(:last_name, :first_name, :address, :company, :phone, :email, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<h1> New Contact </h1>
<%= form_for @contact do |f| %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :company %>
  <%= f.text_field :company %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :notes %>
  <%= f.text_area :notes %>
  
  <%= f.submit %>
<% end %>

app/views/contacts/edit.html.erb
<h1> Edit Contact </h1>
<%= render 'contacts/form' %>
<%= link_to 'Back', contact_path %>

app/views/contacts/index.html.erb
<h1>Contact List</h1>
<h4><%= link_to 'Add Contact', new_contact_path %></h4>
<% @contacts.each do |contact| %>
  <h2><%= "#{contact.last_name},  #{contact.first_name}" %></h2>
  <%= link_to 'Show Contact', contact_path(contact) %>
  
  
  <% end %>

app/views/contacts/new.html.erb
<h1>Add Contact</h1>
<%= render 'contacts/form' %>
<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<h1><%= "#{@contact.first_name} #{@contact.last_name}" %></h1>
<h2><%= "Last Name: #{@contact.last_name}" %></h2>
<h2><%= "First Name: #{@contact.first_name}" %></h2>
<h3><%= "Address: #{@contact.address}" %></h3>
<h3><%= "Company: #{@contact.company}" %></h3>
<h3><%= "Phone: #{@contact.phone}" %></h3>
<h3><%= "Email: #{@contact.email}" %></h3>
<h3><%= "Notes: #{@contact.notes}" %></h3>
<%= link_to 'Back', contacts_path %>
<%= link_to 'Edit', edit_contact_path(@contact.id) %>
<%= link_to 'Delete', @contact, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>